name: Run tests
on:
  pull_request:
    branches:
      - testing
      - development
      - main
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    name: Setup and test project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install 

      - name: Run action
        run: echo "Hello world"

      # - name: Test application
      #   run: npm test

      # - name: Build application
      #   run: |
      #     echo "Run command to build the application if present"
      #     npm run build --if-present